Pages/Admin/AdminDashboard.cshtml.cs
using System.Dynamic;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;
using Microsoft.AspNetCore.Mvc;
using System.Text;

namespace YMCAProject.Pages.Admin
{

public class AdminDashboard : PageModel
{
    private readonly IConfiguration _configuration;
    public AdminDashboard(IConfiguration configuration)
    {
        _configuration = configuration;
    }

    //list of member models for displaying members in grid
    public List<Models.Member> memberList {get; set;} = [];
    //list of MemberPrograms for generating report
    public List<Models.MemberProgram> memberPrograms {get; set;} = [];

    /*
    Author: Cole Hansen
    Date: 12/9/24
    parameters: DateTime start, DateTime end
    function: load memberId, name, programId, className, startDate, and endDate
              from database and load into memberPrograms list and create a csv 
              file.
    returns: success-csv file
             fail: exception    
    */
    public IActionResult OnPostGenerateReport(DateTime start, DateTime end){

        //set end to 30th, 31st, 29th, or 28th of month
        DateTime endDate = new DateTime(end.Year, end.Month, DateTime.DaysInMonth(end.Year, end.Month));
  
        try
        {
            string connectionString = _configuration.GetConnectionString("Default");

            //load memberPrograms data
            using (MySqlConnection connection = new MySqlConnection(connectionString)){
                connection.Open();

                string sql = "SELECT m.MemberId, " +
                             "CONCAT(m.FirstName, ' ', m.LastNAme) AS member_name, " +
                             "p.program_id, p.class_name, p.start_date, p.end_date " +
                             "FROM Members m " + 
                             "JOIN Member_Programs mp ON m.MemberId = mp.MemberId " +
                             "JOIN Programs p ON mp.ProgramId = p.program_id " +
                             "WHERE (p.start_date <= @End) " +
                             "AND (p.end_date >= @Start) "+
                             "ORDER BY m.MemberId, p.start_date;";
                using (MySqlCommand command = new MySqlCommand(sql, connection)){
                    command.Parameters.AddWithValue("@Start", start);
                    command.Parameters.AddWithValue("@End", endDate); 

                    using (MySqlDataReader reader = command.ExecuteReader()) {
                        while(reader.Read()){
                            //read each line of query into memberProgram object
                            var mp = new Models.MemberProgram();

                            mp.MemberId = reader.GetInt32(0);
                            mp.MemberName = reader.GetString(1);
                            mp.ProgramId = reader.GetInt32(2);
                            mp.ClassName = reader.GetString(3);
                            mp.StartDate = reader.GetDateTime(4);
                            mp.EndDate = reader.GetDateTime(5);

                            memberPrograms.Add(mp); // add to list

                        }
                    }
                }


            }

            var csvBuilder = new StringBuilder();

            // Write the CSV headers
             csvBuilder.AppendLine("MemberId,Name,ProgramId,ClassName,StartDate,EndDate");

            // Write the CSV rows
            foreach (var item in memberPrograms)
            {
             csvBuilder.AppendLine($"{item.MemberId}," +
                                  $"{item.MemberName}," +
                                  $"{item.ProgramId}," +
                                  $"{item.ClassName}," +
                                  $"{item.StartDate:yyyy-MM-dd}," +
                                  $"{item.EndDate:yyyy-MM-dd}");
            }

            // Convert the StringBuilder content to a byte array
            byte[] csvBytes = Encoding.UTF8.GetBytes(csvBuilder.ToString());

            // Return the CSV file as a downloadable response
            return File(csvBytes, "text/csv", "MemberPrograms.csv");

        }
        
        catch(Exception ex)
        {
            Console.WriteLine("We have an error generating report: " + ex.Message);
        }
          
        // Show a success message 
        TempData["RegisterMessage"] = $"Report Generated, please check your downloads";
        TempData["MessageType"] = "success";
        
        // Redirect to the same page to show the message
        return RedirectToPage();
    }

    /*
    Author: Kylie Trousil
    Date: 12/13/24
    Parameters: member id, member first name, member last name
    Function: Soft delete user from database and remove any current or future classes they are registered for
    returns: IActionResult - redirect to page and show error/success message
    */
    public IActionResult OnPostDeleteUser(int memberId, string fname, string lname){

        try{
                // connection to database
                string connectionString = _configuration.GetConnectionString("Default");

                using (MySqlConnection connection = new MySqlConnection(connectionString)){
                    connection.Open();

                    // soft delete: adjust isActive member value
                    string sql = "UPDATE Members " +
                        "SET IsActive = 0 " +
                        "WHERE MemberId = @MemberId";

                    using (MySqlCommand command = new MySqlCommand(sql, connection)){
                        command.Parameters.AddWithValue("@MemberId", memberId);
                        
                        command.ExecuteNonQuery();
                    }

                    // remove from current or future programs
                    sql = "DELETE FROM Member_Programs " +
                            "WHERE MemberID = @MemberId AND ProgramID IN (SELECT program_id " +
                                                                            "FROM Programs " +
                                                                            "WHERE NOW() < end_date)";
                    
                    using (MySqlCommand command = new MySqlCommand(sql, connection)){
                        command.Parameters.AddWithValue("@MemberId", memberId);
                        
                        command.ExecuteNonQuery();
                    }
                }

            }
            catch(Exception ex){
                Console.WriteLine("We have an error on delete user: " + ex.Message);
            }

        // Show a success message 
        TempData["RegisterMessage"] = $"{fname} {lname} has been successfully removed";
        TempData["MessageType"] = "success";
        
        // Redirect to the same page to show the message
        return RedirectToPage();
    }

    /*
    Author: Cole Hansen
    Date: 11/13/24
    Parameters: none
    Function: Load members into MemberList on page load
    returns: void
    */
    public void OnGet(){
        try{
                string connectionString = _configuration.GetConnectionString("Default");
                //connection to sql to load members
                using (MySqlConnection connection = new MySqlConnection(connectionString)){

                    connection.Open();

                    string sql = "SELECT * FROM Members";
                    
                    using (MySqlCommand command = new MySqlCommand(sql, connection)){
                        using (MySqlDataReader reader = command.ExecuteReader()) {
                            while (reader.Read()){
                                //read each line from query into member object
                                Models.Member member = new Models.Member();

                                member.MemberId = reader.GetInt32(0);
                                member.FirstName = reader.GetString(1);
                                member.LastName = reader.GetString(2);
                                member.Email = reader.GetString(3);
                                member.PasswordHash = reader.GetString(4);
                                var active = reader.GetInt16(5);
                                var mem = reader.GetInt16(6);

                                if(active == 1){
                                    member.IsActive = true;
                                }else{
                                    member.IsActive = false;
                                }

                                if(mem == 1){
                                    member.IsMember = true;
                                }else{
                                    member.IsMember = false;
                                }

                                memberList.Add(member); //add member to list

                            }
                        }
                    }
                }
        } catch(Exception ex)
        {
            Console.WriteLine("We have an error: " + ex.Message);
        }
    }
}
}

Pages/Admin/CreateProgram.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Org.BouncyCastle.Asn1.Esf;
using Microsoft.Extensions.Configuration; // For configuration
using MySql.Data.MySqlClient;

namespace YMCAProject.Pages.Admin
{
    
    public class CreateProgram : PageModel
    {
        // configuration for sql database
        private readonly IConfiguration _configuration;
        public CreateProgram(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        // new program required information
        [BindProperty, Required(ErrorMessage = "The Program Name is required")]
        public string ClassName { get; set; } = null!;

        [BindProperty, Required(ErrorMessage = "The Program Description is required")]
        public string? ClassDescription { get; set; }

        [BindProperty, Required(ErrorMessage = "The Location is required")]
        public string Location { get; set; } = null!;

        [BindProperty, Required(ErrorMessage = "The Price for Members is required"), Range(1, int.MaxValue, ErrorMessage = "The price must be greater than 0")]
        public double PriceMember { get; set; }

        [BindProperty, Required(ErrorMessage = "The Price for Non-members is required"), Range(1, int.MaxValue, ErrorMessage = "The price must be greater than 0")]
        public double PriceNonmember { get; set; }

        [BindProperty, Required(ErrorMessage = "Capacity is required"), Range(1, int.MaxValue, ErrorMessage = "The capacity must be greater than 0")]
        public int Capacity { get; set; }

        [BindProperty, Required(ErrorMessage = "The Day of Week is required")]
        public List<string> Days { get; set; } = null!;

        [BindProperty, Required(ErrorMessage = "Start Date is required"), CustomValidation(typeof(CreateProgram), nameof(ValidateStartDate))]
        public DateTime StartDate { get; set; }

        [BindProperty, Required(ErrorMessage = "End Date is required"), CustomValidation(typeof(CreateProgram), nameof(ValidateEndDate))]
        public DateTime EndDate { get; set; }

        [BindProperty, Required(ErrorMessage = "Start Time is required")]
        public DateTime StartTime { get; set; }

        [BindProperty, Required(ErrorMessage = "End Time is required"), CustomValidation(typeof(CreateProgram), nameof(ValidateEndTime))]
        public DateTime EndTime { get; set; }

        /*
        Author: Kylie Trousil
        Date: 11/13/24
        Parameters: start date, validation context
        Function: Data validation - ensure start date of program is after today
        returns: ValidationResult - success or error
        */
        public static ValidationResult ValidateStartDate(DateTime startDate, ValidationContext context)
        {
            if (startDate <= DateTime.Today)
            {   
                Console.WriteLine($"Start Date: {startDate}");
                return new ValidationResult("Start date must be after today");
            }

            return ValidationResult.Success;
        }

        /*
        Author: Kylie Trousil
        Date: 11/13/24
        Parameters: end date, validation context
        Function: Data validation - ensure end date of program is after the start date
        returns: ValidationResult - success or error
        */
        public static ValidationResult ValidateEndDate(DateTime endDate, ValidationContext context)
        {
            var instance = context.ObjectInstance as CreateProgram;
            if (instance != null && instance.StartDate >= endDate)
            {
                Console.WriteLine($"Start Date: {instance.StartDate}");
                Console.WriteLine($"End Date: {endDate}");
                return new ValidationResult("End date must be after start date");
            }

            return ValidationResult.Success;
        }

        /*
        Author: Kylie Trousil
        Date: 11/13/24
        Parameters: end time, validation context
        Function: Data validation - ensure end time is after start time
        returns: ValidationResult - success or error
        */
        public static ValidationResult ValidateEndTime(DateTime endTime, ValidationContext context)
        {
            var instance = context.ObjectInstance as CreateProgram;

            if (instance != null && instance.StartTime >= endTime)
            {
                Console.WriteLine($"Start Time: {instance.StartTime}");
                Console.WriteLine($"End Time: {endTime}");
                return new ValidationResult("End time must be after start time");
            }

            return ValidationResult.Success;
        }

        public void OnGet()
        {        }

        /*
        Author: Kylie Trousil
        Date: 10/9/24 (updated: 11/13/24)
        Parameters: none
        Function: on submit button click, add new program to database
        returns: void
        */
        public void OnPost()
        {
            // data validation - ensure day of week is selected
            if (Days.Count < 1 || Days[0] is null)
            {
                ModelState.AddModelError("Days", "The Day of Week is required");
            }
            // data validation - check model state has no errors
            if (!ModelState.IsValid){
                Console.WriteLine("Error: Model State is not valid");
                return;
            }

            string daysAsString = string.Join(",", Days);

            // create new program
            try{
                string connectionString = _configuration.GetConnectionString("Default");

                using (MySqlConnection connection = new MySqlConnection(connectionString)){
                    connection.Open();

                    string sql = "Insert INTO Programs " +
                        "(class_name, class_description, staff_id, price_member, price_nonmember, capacity, start_date, end_date, start_time, end_time, location, days, status) VALUES " +
                        "(@ClassName, @ClassDescription, @StaffId, @PriceMember, @PriceNonmember, @Capacity, @StartDate, @EndDate, @StartTime, @EndTime, @Location, @Days, @Status)";

                    using (MySqlCommand command = new MySqlCommand(sql, connection)){
                        command.Parameters.AddWithValue("@ClassName", ClassName);
                        command.Parameters.AddWithValue("@ClassDescription", ClassDescription); 
                        command.Parameters.AddWithValue("@StaffId", 1);
                        command.Parameters.AddWithValue("@PriceMember", PriceMember); 
                        command.Parameters.AddWithValue("@PriceNonmember", PriceNonmember); 
                        command.Parameters.AddWithValue("@Capacity", Capacity); 
                        command.Parameters.AddWithValue("@StartDate", StartDate); 
                        command.Parameters.AddWithValue("@EndDate", EndDate); 
                        command.Parameters.AddWithValue("@StartTime", StartTime); 
                        command.Parameters.AddWithValue("@EndTime", EndTime);
                        command.Parameters.AddWithValue("@Location", Location); 
                        command.Parameters.AddWithValue("@Days", daysAsString);
                        command.Parameters.AddWithValue("@Status", 1);
                        
                        command.ExecuteNonQuery();
                    }
                }

            }
            catch(Exception ex){
                Console.WriteLine("We have an error: " + ex.Message);
                return;
            }

            // redirect to programs page
            Response.Redirect("/Programs");
        }
    }
}

Pages/Admin/AdminDashboard.cshtml
@page
@model YMCAProject.Pages.Admin.AdminDashboard
@{
    ViewData["Title"] = "Admin Dashboard";
}

<h1> Admin Dashboard</h1>

@if (TempData["RegisterMessage"] != null)
{
    <div class="alert @((string)TempData["MessageType"] == "success" ? "alert-success" : "alert-danger")">
        @TempData["RegisterMessage"]
    </div>
}

<div class="container">
    <table style="border: 1px black solid">
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Member Status</th>
            <th>View Classes</th>
            <th>Edit User</th>
        </tr>
    @foreach (var member in Model.memberList){
        if(member.IsActive == false) {continue;} //skip inactive members
        <tr>
            <td>@member.FirstName</td>
            <td>@member.LastName</td>
            <td>@member.Email</td>
            <td>@(member.IsMember ? "Member" : "Non-Member")</td>
            
            <td><a class='btn btn-primary mb-3' href='/MemberDashboard?id=@member.MemberId'>View Programs</a></td>
            <td><form method="post" asp-page-handler="DeleteUser">
                <input type="hidden" name="memberId" value="@member.MemberId" />
                <input type="hidden" name="fname" value="@member.FirstName" />
                <input type="hidden" name="lname" value="@member.LastName" />
                <button type="submit" class="btn btn-outline-primary">Remove User</button>
            </form></td>
        </tr> 

    }
    </table>
</div>       
<div class="report-container">

    <form method="post" asp-page-handler="GenerateReport">
        <input type="month" name="start" value="2024-09">
        <input type="month" name="end" value="2024-11">
        <button type="submit" class="btn btn-outline-primary">Generate Program Report</button>
    </form>

</div> 

<style>
    table{
        align-items: center;
        width: 100%;
        border: solid 1px black;

    }

    tr{border-bottom: solid 1px black;}

    tr:nth-child(2n){background-color: lightgray;}

    a{padding-top:10px;}

    .report-container{
        padding-top: 20px;
    }

    
</style>

Pages/Admin/CreateProgram.cshtml
@page
@model YMCAProject.Pages.Admin.CreateProgram
@{
    ViewData["Title"] = "CreateProgram";
}

<div class="row">
    <div class="col-md mx-auto rounded border p-4">
        <h2 class="text-center mb-5">New Program</h2>

        @* form to create program *@
        <form method="post">
            <div class="row mb-3">
                <label class="col-sm-4 col-form-label">Program Name*</label>
                <div class="col-sm-8">
                    <input class="form-control" asp-for="ClassName"/>
                    <span asp-validation-for="ClassName" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-sm-4 col-form-label">Program Description*</label>
                <div class="col-sm-8">
                    <input class="form-control" asp-for="ClassDescription" />
                    <span asp-validation-for="ClassDescription" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-sm-4 col-form-label">Location*</label>
                <div class="col-sm-8">
                    <input class="form-control" asp-for="Location" />
                    <span asp-validation-for="Location" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-sm-4 col-form-label">Day of Week*</label>
                <div class="col-sm-8">
                     <select class="form-control" asp-for="Days" multiple size="8">
                        <option value="">-- Select a day (ctrl for multi-select) -- </option>
                        <option value="Monday">Monday</option>
                        <option value="Tuesday">Tuesday</option>
                        <option value="Wednesday">Wednesday</option>
                        <option value="Thursday">Thursday</option>
                        <option value="Friday">Friday</option>
                        <option value="Saturday">Saturday</option>
                        <option value="Sunday">Sunday</option>
                    </select>
                    <span asp-validation-for="Days" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-sm-2 col-form-label">Price (Member)*</label>
                <div class="col-sm-4">
                    <input class="form-control" asp-for="PriceMember" />
                    <span asp-validation-for="PriceMember" class="text-danger"></span>
                </div>

                <label class="col-sm-2 col-form-label">Price (Non-member)*</label>
                <div class="col-sm-4">
                    <input class="form-control" asp-for="PriceNonmember" />
                    <span asp-validation-for="PriceNonmember" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-sm-2 col-form-label">Capacity*</label>
                <div class="col-sm-4">
                    <input class="form-control" asp-for="Capacity" />
                    <span asp-validation-for="Capacity" class="text-danger"></span>
                </div>
            </div>

            

            <div class="row mb-3">
                <label class="col-sm-2 col-form-label">Start Date*</label>
                <div class="col-sm-4">
                    <input class="form-control" asp-for="StartDate" type="date" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
      
                <label class="col-sm-2 col-form-label">End Date*</label>
                <div class="col-sm-4">
                    <input class="form-control" asp-for="EndDate" type="date" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-sm-2 col-form-label">Start Time*</label>
                <div class="col-sm-4">
                    <input class="form-control" asp-for="StartTime" type="time" />
                    <span asp-validation-for="StartTime" class="text-danger"></span>
                </div>

                <label class="col-sm-2 col-form-label">End Time*</label>
                <div class="col-sm-4">
                    <input class="form-control" asp-for="EndTime" type="time" />
                    <span asp-validation-for="EndTime" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="offset-sm-4 col-sm-4 d-grid">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
                <div class="col-sm-4 d-grid">
                    <a class="btn btn-outline-primary" href="/Programs" role="button">Cancel</a>
                </div>
            </div>
        </form>
    
    </div>
    
</div>