Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace YMCAProject.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/MemberDashboard.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;

namespace YMCAProject.Pages;

public class MemberDashboard : PageModel
{
    // private readonly ILogger<MemberDashboard> _logger;

    // public MemberDashboard(ILogger<MemberDashboard> logger)
    // {
    //     _logger = logger;
    // }

    private readonly IConfiguration _configuration;
    public MemberDashboard(IConfiguration configuration)
    {
        _configuration = configuration;
    }

    public List<Models.Programs> programList {get; set;} = [];
    public int IsMember { get; set; } //Property to store the isMember value
    public String FirstName {get; set;} //Store first name
    public int MemberId { get; set; }

     /* 
     * Cancel Class Button
     *
     * Input: programID, userId
     * Return: Nothing
     */
    public IActionResult OnPostCancelRegistration(int userId, int programId)
    {
        try{
                string connectionString = _configuration.GetConnectionString("Default");

                using (MySqlConnection connection = new MySqlConnection(connectionString)){
                    connection.Open();

                    // change status to 0
                    string sql = "DELETE FROM Member_Programs WHERE MemberId = @UserId AND ProgramId = @ProgramId";

                    using (MySqlCommand command = new MySqlCommand(sql, connection))
                    {
                        command.Parameters.AddWithValue("@UserId", userId);
                        command.Parameters.AddWithValue("@ProgramId", programId);

                        int rowsAffected = command.ExecuteNonQuery();
                        if (rowsAffected > 0)
                        {
                            TempData["RegisterMessage"] = "Success: Your registration has been canceled.";
                            TempData["MessageType"] = "success";
                        }
                        else
                        {
                            TempData["RegisterMessage"] = "Error: No registration found to cancel.";
                            TempData["MessageType"] = "error";
                        }
                    }
                }
            }
            catch (Exception ex)
            {       
                Console.WriteLine("Error: " + ex.Message);
                TempData["RegisterMessage"] = "Error: An exception occurred while trying to cancel your registration.";
                TempData["MessageType"] = "error";
            }

            return RedirectToPage();
    }

    /* 
     * Get User Programs to Display
     *
     * Input: Nothing
     * Return: Data to display
     */
    public void OnGet(string? id = null)
    {
        try{
                string connectionString = _configuration.GetConnectionString("Default");

                using (MySqlConnection connection = new MySqlConnection(connectionString)){

                    connection.Open();

                    //get the currently logged in users ID
                    int memberId = int.Parse(User.FindFirst("UserId")?.Value);
                    MemberId = memberId;

                    //Query to get isMember status
                    string memberQuery = "SELECT isMember FROM ymca.Members WHERE MemberId = @UserId";
                    using (MySqlCommand memberCommand = new MySqlCommand(memberQuery, connection))
                    {
                        memberCommand.Parameters.AddWithValue("@UserId", memberId);
                        IsMember = Convert.ToInt32(memberCommand.ExecuteScalar());
                    }

                    //Query to get first name
                    string nameQuery = "SELECT FirstName FROM ymca.Members WHERE MemberId = @UserId";
                    using (MySqlCommand memberCommand = new MySqlCommand(nameQuery, connection))
                    {
                        memberCommand.Parameters.AddWithValue("@UserId", memberId);
                        FirstName = memberCommand.ExecuteScalar()?.ToString();
                    }

                    //Query to get program details
                    string sql = @"SELECT p.*, 
                       (p.capacity - COALESCE(m.registered_count, 0)) AS `spotsLeft`
                        FROM ymca.Programs p
                        INNER JOIN Member_Programs mp ON p.program_id = mp.ProgramId
                        LEFT JOIN (
                            SELECT ProgramId, COUNT(MemberId) AS registered_count 
                            FROM Member_Programs 
                            GROUP BY ProgramId
                        ) m ON p.program_id = m.ProgramId
                        WHERE mp.MemberId = @MemberId";

                    using (MySqlCommand command = new MySqlCommand(sql, connection)){
                        //add users MemberId as a parameter to the query
                        if(string.IsNullOrEmpty(id)){
                            command.Parameters.AddWithValue("@MemberId", memberId);
                        }else 
                        {
                            command.Parameters.AddWithValue("@MemberId", int.Parse(id));
                        }

                        //retrieve data for prorgams the user is registered for
                        using (MySqlDataReader reader = command.ExecuteReader()) {
                            while (reader.Read()){

                                Models.Programs classInfo = new Models.Programs();

                                classInfo.ProgramId = reader.GetInt32(0);
                                classInfo.ClassName = reader.GetString(1);
                                classInfo.ClassDescription = reader.GetString(2);
                                classInfo.StaffId = reader.GetInt16(3);
                                classInfo.Capacity = reader.GetInt32(6);
                                classInfo.StartDate = reader.GetDateTime(7);
                                classInfo.EndDate = reader.GetDateTime(8);
                                classInfo.StartTime = reader.GetDateTime(9);
                                classInfo.EndTime = reader.GetDateTime(10);
                                classInfo.Location = reader.GetString(11);
                                classInfo.Days = reader.GetString(12);
                                classInfo.SpotsLeft = reader.GetInt32(13);
                                classInfo.Status = reader.GetInt32(13);

                                programList.Add(classInfo);
                            }
                        }
                    }
                }

            }
            catch(Exception ex){
                Console.WriteLine("We have an error: " + ex.Message);
            }
    }
}

Pages/Membership.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace YMCAProject.Pages;

public class MembershipModel : PageModel
{
    private readonly ILogger<MembershipModel> _logger;

    public MembershipModel(ILogger<MembershipModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

Pages/Programs.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;
using YMCAProject.Models;

namespace YMCAProject.Pages;

public class ProgramsModel : PageModel
{
    // sql connection
    private readonly IConfiguration _configuration;
    public ProgramsModel(IConfiguration configuration)
    {
        _configuration = configuration;
    }

    // program page filters
    [BindProperty(SupportsGet = true)]
    public string SearchName { get; set; }

    [BindProperty(SupportsGet = true)]
    public List<string> DayOfWeek { get; set; }

    [BindProperty(SupportsGet = true)]
    public DateTime? StartDateFrom { get; set; } = DateTime.Today; // default to today

    [BindProperty(SupportsGet = true)]
    public DateTime? StartDateTo { get; set; } = DateTime.Today.AddYears(1); // default to year after today

    [BindProperty(SupportsGet = true)]
    public int Status { get; set; } = 1;

    // check is staff member
    public bool isStaff = false;
    // list of family members
    public List<Member> FamilyMembers { get; set; } = new();
    // list of programs to display
    public List<Programs> programList {get; set;} = new List<Programs>();


    /*
    Author: Kylie Trousil
    Date: 10/9/24 (last updated: 12/6/24)
    Parameters: member id, class name, program id, start date, start time, days of week
    Function: On register button click, verify no schedule conflicts and register user for program
    returns: IActionResult - redirect to same page and display success or error message
    */
    public IActionResult OnPostRegisterClass(int memberId, string className, int programId, DateTime startDate, DateTime startTime, string days)
    {
        // select member who is registering for course
        LoadFamilyMembers();
        Member mem = FamilyMembers.FirstOrDefault(m => m.MemberId == memberId);

        try{
            // connection to databse
            string connectionString = _configuration.GetConnectionString("Default");

            using (MySqlConnection connection = new MySqlConnection(connectionString)){
                connection.Open();

                // check if member is already registered for the course
                string sql = "SELECT Count(*) FROM Member_Programs " +
                    "WHERE MemberId = @MemberId AND ProgramID = @ProgramId ";

                using (MySqlCommand command = new MySqlCommand(sql, connection)){
                    command.Parameters.AddWithValue("@MemberId", mem.MemberId);
                    command.Parameters.AddWithValue("@ProgramId", programId); 

                    using (MySqlDataReader reader = command.ExecuteReader()) {
                        reader.Read();
                        int count = reader.GetInt32(0);

                        if (count > 0){
                            // Show a failure message 
                            TempData["RegisterMessage"] = $"Error: {mem.FirstName} {mem.LastName} is already registered for {className}";
                            TempData["MessageType"] = "error";
                            
                            // Redirect to the same page to show the message
                            return RedirectToPage();
                        }

                    }
                }

                // check for schedule conflicts
                sql = "SELECT p.program_id, p.class_name, p.days, p.start_date, p.end_date, p.start_time, p.end_time " +
                        "FROM Programs p " +
                        "JOIN Member_Programs mp on p.program_id = mp.ProgramId " +
                        "WHERE mp.MemberId = @MemberId " +
                            "AND (@startDate BETWEEN p.start_date AND p.end_date) " +
                            "AND (TIME(@startTime) BETWEEN TIME(p.start_time) AND TIME(p.end_time))";

                string[] dayArray = days.Split(',');

                using (MySqlCommand command = new MySqlCommand(sql, connection)) {
                    command.Parameters.AddWithValue("@MemberId", mem.MemberId);
                    command.Parameters.AddWithValue("@startDate", startDate);         
                    command.Parameters.AddWithValue("@startTime", startTime); 


                    using (MySqlDataReader reader = command.ExecuteReader()) {
                        while(reader.Read()){
                            string curClass = reader.GetString(1);
                            string programDays = reader.GetString(2);

                            foreach (var day in dayArray)
                            {
                                int index = programDays.IndexOf(day);
                                if (index != -1){
                                    // Show a failure message 
                                    TempData["RegisterMessage"] = $"Error: unable to register for {className} because it overlaps with {curClass}";
                                    TempData["MessageType"] = "error";
                                        
                                    // Redirect to the same page to show the message
                                    return RedirectToPage();
                                }

                            }
                        }
                    }
                }

                // register member for program
                sql = "Insert INTO Member_Programs " +
                    "(MemberId, ProgramId) VALUES " +
                    "(@MemberId, @ProgramId)";

                using (MySqlCommand command = new MySqlCommand(sql, connection)){
                    command.Parameters.AddWithValue("@MemberId", mem.MemberId); 
                    command.Parameters.AddWithValue("@ProgramId", programId); 
                    
                    command.ExecuteNonQuery();
                }
            }
        }
        
        catch(Exception ex){
            Console.WriteLine("We have a sql error in register class: " + ex.Message);
        }

        // Show a success message 
        TempData["RegisterMessage"] = $"{mem.FirstName} {mem.LastName} is successfully registered for {className}!";
        TempData["MessageType"] = "success";
        
        // Redirect to the same page to show the message
        return RedirectToPage();
    }

    /*
    Author: Kylie Trousil
    Date: 11/13/24
    Parameters: program id, class name
    Function: On cancel button click, soft delete class by updating class status
    returns: IActionResult - redirect to same page and display success or error message
    */
    public IActionResult OnPostCancelClass(int programId, string className)
    {
        try{
            // connection to sql database
            string connectionString = _configuration.GetConnectionString("Default");

            using (MySqlConnection connection = new MySqlConnection(connectionString)){
                connection.Open();

                // change status to 0
                string sql = "UPDATE Programs SET status = 0 " +
                            "WHERE program_id = @ProgramId ";

                using (MySqlCommand command = new MySqlCommand(sql, connection)){
                    command.Parameters.AddWithValue("@ProgramId", programId); 

                    command.ExecuteNonQuery();
                }
            }

            // Show a success message 
            TempData["RegisterMessage"] = $"Success: {className} has been canceled and all members will be notified on their dashboard";
            TempData["MessageType"] = "success";
        }
        catch(Exception ex){
            Console.WriteLine("We have an error: " + ex.Message);
            // Show an error message 
            TempData["RegisterMessage"] = $"Error: An exception has occured when trying to cancel {className}";
            TempData["MessageType"] = "error";
        }
        
        // Redirect to the same page and show the message
        return RedirectToPage();
    }

    /*
    Author: Kylie Trousil
    Date: 10/9/24 (last updated 12/9/24)
    Parameters: 
    Function: On page load, load all programs and family members
    returns: void
    */
    public void OnGet()
    {
        // check if user on staff
        if ((User.FindFirst("UserType")?.Value?.Equals("Admin") ?? false) || (User.FindFirst("UserType")?.Value?.Equals("Staff") ?? false)){
            isStaff = true;
        }
        // if member or non-member, load family members
        if ((User.FindFirst("UserType")?.Value?.Equals("Member") ?? false) || (User.FindFirst("UserType")?.Value?.Equals("non-member") ?? false)){
            LoadFamilyMembers();
        }

        try{
            // sql database connection
            string connectionString = _configuration.GetConnectionString("Default");

            using (MySqlConnection connection = new MySqlConnection(connectionString)){
                connection.Open();
                // Get Programs list
                string sql = "SELECT p.*, (p.capacity - COALESCE(m.registered_count, 0)) AS `spotsLeft`" +
                    "FROM ymca.Programs p LEFT JOIN ( " +
                        "SELECT ProgramId, COUNT(MemberId) AS registered_count FROM Member_Programs GROUP BY ProgramId" +
                    ") m ON p.program_id = m.ProgramId WHERE status = @Status ORDER BY p.class_name;";

                using (MySqlCommand command = new MySqlCommand(sql, connection)){
                    command.Parameters.AddWithValue("@Status", Status);

                    using (MySqlDataReader reader = command.ExecuteReader()) {
                        while (reader.Read()){
                            Programs classInfo = new Programs();

                            classInfo.ProgramId = reader.GetInt32(0);
                            classInfo.ClassName = reader.GetString(1);
                            classInfo.ClassDescription = reader.GetString(2);

Pages/CreateMember.cshtml
@page
@model YMCAProject.Pages.CreateMember
@{
    ViewData["Title"] = "CreateMember";
}

<div>
    <h2 class="text-center mb-5">New Member</h2>

        @* create member form *@
        <form method="post">

            <div class="row mb-3">
                <label class="col-sm-4 col-form-label">First Name*</label>
                <div class="col-sm-8">
                    <input class="form-control" asp-for="FirstName"/>
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-sm-4 col-form-label">Last Name*</label>
                <div class="col-sm-8">
                    <input class="form-control" asp-for="LastName" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-sm-4 col-form-label">Email*</label>
                <div class="col-sm-8">
                    <input class="form-control" asp-for="Email" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-sm-4 col-form-label">Password*</label>
                <div class="col-sm-8">
                    <input class="form-control" asp-for="Password" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-sm-4 col-form-label">Membership Option*</label>
                <div class="col-sm-8">
                     <select class="form-control" asp-for="IsMember">
                        <option value="1">Member</option>
                        <option value="0">Non-Member</option>
                    </select>
                    <span asp-validation-for="IsMember" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="offset-sm-4 col-sm-4 d-grid">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
                <div class="col-sm-4 d-grid">
                    <a class="btn btn-outline-primary" href="/Membership" role="button">Cancel</a>
                </div>
            </div>
        </form>
    
</div>

Pages/Login.cshtml
@page
@model YMCAProject.Pages.LoginModel
@{
    ViewData["Title"] = "Login";
}
<h2>Login</h2>
<form method="post">
    <div>
        <label asp-for="Email"></label>
        <input asp-for="Email" />
        <span asp-validation-for="Email"></span>
    </div>
    <div>
        <label asp-for="Password"></label>
        <input asp-for="Password" type="password" />
        <span asp-validation-for="Password"></span>
    </div>

    <button type="submit" name="action" value="staff">Staff Login</button>
    <button type="submit" name="action" value="user">User Login</button>
</form>

Pages/Logout.cshtml
@page
@model YMCAProject.Pages.LogoutModel
@{
    ViewData["Title"] = "Logout";
}
<form method="post">
    <button type="submit">Logout</button>
</form>

Pages/MemberDashboard.cshtml
@page
@using YMCAProject.Models
@model YMCAProject.Pages.MemberDashboard
@{
    ViewData["Title"] = "MemberDashboard";
}

<!-- Display different title based upon if Member or Non Member  -->
@if (User.Identity.IsAuthenticated) {
    <h1>@(Model.IsMember == 1 ? "Member Dashboard" : "User Dashboard")</h1>
}
<p>Welcome @Model.FirstName! Here you can view all of the programs you are registered for!</p>

<div class="container">
    <div class="row">
        <!-- Display Programs User is registered for  -->
        @foreach (var classInfo in Model.programList)
        {
            <div class="col-lg-4  mb-3">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">@classInfo.ClassName</h5>
                        <p class="card-text"><strong>Description:</strong> @classInfo.ClassDescription</p>
                        <p class="card-text"><strong>Dates:</strong> @classInfo.StartDate.ToString("MMM dd, yyyy") - @classInfo.EndDate.ToString("MMM dd, yyyy")</p>
                        <p class="card-text"><strong>Day/Time:</strong> @classInfo.Days: @classInfo.StartTime.ToString("hh:mm tt") - @classInfo.EndTime.ToString("hh:mm tt")</p>
                        <p class="card-text"><strong>Location:</strong> @classInfo.Location</p>
                        @if (classInfo.Status == 0)
                        {
                            <p class="card-text" style="color: red;"><strong>Status: Cancelled</strong></p>
                        }
                        else if (classInfo.Status == 1)
                        {
                            <p class="card-text" style="color: green;"><strong>Status: Active</strong></p>
                        }
                        <form method="post" asp-page-handler="CancelRegistration">
                            <input type="hidden" name="programId" value="@classInfo.ProgramId" />
                            <input type="hidden" name="userId" value="@Model.MemberId" />
                            <button type="submit" class="btn btn-danger">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Pages/Programs.cshtml
@page
@model YMCAProject.Pages.ProgramsModel
@{
    ViewData["Title"] = "Programs";
}

<style>
    .filter-form {
        background-color: #f1f1f1; /* Light gray background for filter box*/
        padding: 15px;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }
</style>

<h1>Programs Page</h1>
<p>Welcome to the Programs page. Here you can learn more about our program offerings.</p>
<!-- Admin/Staff can Create New Programs -->
@if(Model.isStaff){
    <a class='btn btn-primary mb-3' href='/Admin/CreateProgram'>Create New Program</a>
}
<!-- Success/Alert Messages -->
@if (TempData["RegisterMessage"] != null)
{
    <div class="alert @((string)TempData["MessageType"] == "success" ? "alert-success" : "alert-danger")">
        @TempData["RegisterMessage"]
    </div>
}

<form method="get" class="filter-form">
    <div class="row mb-4">
        <!-- Search by Program Name -->
        <div class="col-md-5">
            <label for="searchName">Search by Keyword</label>
            <input type="text" name="searchName" class="form-control" placeholder="Program Name" value="@Model.SearchName" /> 
        </div>

        <!-- Filter by Day of the Week -->
        <div class="col-md-3">
            <label for="dayOfWeek">Select Days of the Week</label>
            <select name="dayOfWeek" class="form-control" multiple size=7>
                <option value="Monday">Monday</option>
                <option value="Tuesday">Tuesday</option>
                <option value="Wednesday">Wednesday</option>
                <option value="Thursday">Thursday</option>
                <option value="Friday">Friday</option>
                <option value="Saturday">Saturday</option>
                <option value="Sunday">Sunday</option>
            </select>
        </div>

        <!-- Start Date Range -->
        <div class="col-md-2">
            <label for="startDateFrom">Start Date From</label>
            <input type="date" name="startDateFrom" class="form-control" placeholder="Start Date From"  value="@Model.StartDateFrom?.ToString("yyyy-MM-dd")"/>
        
            <label for="startDateTo" style="margin-top: 20px;">Start Date To</label>
            <input type="date" name="startDateTo" class="form-control" placeholder="Start Date To" value="@Model.StartDateTo?.ToString("yyyy-MM-dd")" />
 
             @if((User.FindFirst("UserType")?.Value?.Equals("Admin") ?? false)){
                <label for="status" style="margin-top: 20px;">Class Status</label>
                <select name="status" class="form-select">
                    <option value="1" >Active/Scheduled</option>
                    <option value="0" >Canceled</option>

                </select>
            }
        </div>

        <!-- Filter/Submit Button -->
        <div class="col-md-2 text-right">
            <button type="submit" class="btn btn-primary mb-3">Filter</button>
        </div>
    </div>
</form>

<div style="height: 20px;"></div>

<!-- Display Programs  -->
<div class="container">
    <div class="row">
        @foreach (var classInfo in Model.programList)
        {
            <div class="col-lg-4  mb-3">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">@classInfo.ClassName</h5>
                        <p class="card-text"><strong>Description:</strong> @classInfo.ClassDescription</p>
                        <p class="card-text"><strong>Dates:</strong> @classInfo.StartDate.ToString("MMM dd, yyyy") - @classInfo.EndDate.ToString("MMM dd, yyyy")</p>
                        <p class="card-text"><strong>Day/Time:</strong> @classInfo.Days: @classInfo.StartTime.ToString("hh:mm tt") - @classInfo.EndTime.ToString("hh:mm tt")</p>
                        <p class="card-text"><strong>Location:</strong> @classInfo.Location</p>
                        <p class="card-text"><strong>Price (Member):</strong> $@classInfo.PriceMember</p>
                        <p class="card-text"><strong>Price (Non-member):</strong> $@classInfo.PriceNonmember</p>
                        <p class="card-text"><strong>Spots Left:</strong> @classInfo.SpotsLeft</p>

                        <div class="row">
                            @* if admin/staff, show cancel button *@
                            @if( Model.isStaff && (@classInfo.Status != 0)){
                                <div class="col-sm-4 d-grid">
                                    <form method="post" asp-page-handler="CancelClass">
                                        <input type="hidden" name="programId" value="@classInfo.ProgramId" />
                                        <input type="hidden" name="className" value="@classInfo.ClassName" />
                                        <button type="submit" class="btn btn-outline-primary">Cancel</button>
                                    </form>
                                </div>
                            }
                            @* if member/nonmember, show register button *@
                            else if (User.FindFirst("UserType")?.Value != null){
                                    @if ((@classInfo.SpotsLeft > 0) && (@classInfo.StartDate > @DateTime.Now)){
                                        <form method="post" asp-page-handler="RegisterClass">
                                            <div class= "row align-items-center">
                                                <!-- Family Dropdown -->
                                                <div class="col-sm-8">
                                                    <label for="dropdownOption" class="form-label visually-hidden">Family Member:</label>
                                                    <select id="dropdownOption" name="memberId" class="form-select" required>
                                                        <option value="" disabled selected>Select a Family Member</option>
                                                        @foreach (var option in Model.FamilyMembers)
                                                        {
                                                            <option value="@option.MemberId">@option.FirstName @option.LastName</option>
                                                        }
                                                    </select>
                                                </div>
                                                <!-- Register Button  -->
                                                <div class="col-sm-4">
                                                    <button type="submit" class="btn btn-primary">Register</button>
                                                </div>
                                            </div>

                                            <input type="hidden" name="className" value="@classInfo.ClassName" />
                                            <input type="hidden" name="programId" value="@classInfo.ProgramId" />
                                            <input type="hidden" name="startDate" value="@classInfo.StartDate" />
                                            <input type="hidden" name="startTime" value="@classInfo.StartTime" />
                                            <input type="hidden" name="days" value="@classInfo.Days" />
                                        </form>
                                    }
                                
                            }
                            
                        </div>

                        
                    </div>
                </div>
            </div>
        }
    </div>
</div>